# Site Settings
title: Unidecode | Experimentando y compartiendo usando azucar sintáctico
# email: youremail@xyz.com
description: Some text about your blog.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://unidecode.github.io" # the base hostname & protocol for your site
google_analytics: "UA-126220967-1"

# User Settings
username: Unidecode
user_description: Experimentando y compartiendo usando azucar sintáctico
disqus_username: cnexans

# Social Media
# Remove the item if you don't need it
github_username: unidecode-org
# facebook_username: facebook_username
twitter_username: unidecode
# instagram_username: instagram_username
# linkedin_username: linkedin_username
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

plugins:
  - jekyll-redirect-from

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
